# Generated by Django 5.2.8 on 2026-01-26 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.FloatField()),
                ('total_expense', models.FloatField()),
                ('total_emi', models.FloatField()),
                ('savings', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.userinput')),
            ],
        ),
    ]
