# Generated by Django 5.2.8 on 2025-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='allocation_percent',
            field=models.FloatField(default=0),
        ),
    ]
