# Generated by Django 5.2.8 on 2025-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_savingsgoal_allocation_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='saved_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
