# Generated by Django 5.2.8 on 2026-02-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0006_financerecord_fixed_obligations_emiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='spending_behaviour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
