# Generated by Django 5.2.8 on 2026-02-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0007_financerecord_spending_behaviour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financerecord',
            old_name='savings',
            new_name='net_balance',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='emi_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='savings_behaviour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
